### PR TITLE
Fix send function in py3

### PR DESCRIPTION
**Pull request by OpenSPA**
Changed the send function of the socket that has to be in bytes instead of str.

### CODE REVIEW

**Comment by OpenSPA** [comment]
More changes are necessary to be able to turn off the lights, we are working on it.

**Comment by OpenSPA** [comment]
Add fix turning off the lights.

**Comment by OpenSPA** [comment]
Add fix moodlamp mode.

**Comment by nickersk** [comment]
thank you, squashed locally and pushed here...

**Pull request closed without merging**
